REPLACE INTO `cosmicPortfolio`.`star` 
(`starID`, `Name`, `Description`, `xPosition`, `yPosition`, `zPosition`, `modleName`, `Size`, `imageURL`) 
VALUES 
(1, 'Project 1', 'In a world where technology evolves at an unprecedented pace, developers find themselves constantly adapting to new frameworks, languages, and paradigms, striving to write efficient, maintainable, and scalable code that not only meets the demands of modern applications but also anticipates future challenges; however, the complexity of software development often introduces unforeseen bugs, performance bottlenecks, and integration issues that require thorough testing, debugging, and optimization, ensuring that every function, module, and system operates seamlessly across different environments, devices, and user scenarios, thereby reducing technical debt and enhancing user experience, which, in turn, fosters greater adoption, satisfaction, and engagement, making it imperative for programmers, engineers, and architects to stay informed about best practices, industry trends, and emerging technologies, such as artificial intelligence, machine learning, blockchain, and quantum computing, all of which have the potential to revolutionize the way we approach problem-solving, automation, and data analysis, leading to more intelligent, adaptive, and personalized applications that can anticipate user needs, improve decision-making processes, and enhance overall efficiency, productivity, and innovation, thereby pushing the boundaries of what is possible in the digital realm, transforming industries such as healthcare, finance, education, and entertainment, and ultimately reshaping the way we live, work, and interact with technology on a daily basis.', 80, 10, -65, 'star_models/test_model_1', .5, 'example1.webp,example2.webp'),
(2, 'Project 2', 'This is place holder example text', 120, 15, -32, 'star_models/test_model_2', .5, 'example1.webp'),
(3, 'Project 3', 'This is place holder example text', 80, 5, -80, 'star_models/test_model_3', .5, 'example1.webp'),
(4, 'Project 4', 'This is place holder example text', 90, 50, -80, 'star_models/test_model_4', .5, 'example1.webp'),
(5, 'Project 5', 'This is place holder example text', 90, 50, -30, 'star_models/test_model_5', .5, 'example1.webp'),
(6, 'Project 6', 'This is place holder example text', 100, 30, -31, 'star_models/test_model_6', .5, 'example1.webp');
